### ISSUE TITLE
Tests fail for Python3 only systems and do not respect the Python3 version

### ISSUE THREAD

**Issue by gerion0** [stettberger/versuchung#18]
Appearently, invoking `./setup.py test` triggers tests for Python 2 and Python 3 (actually for the `python2` and `python3` symlinks).

On my system the package is built multiple times for different python versions. This is done by invoking `setup.py` multiple times with the specific Python version, e.g.: `pypy3 setup.py test --verbose` (and alias the standard symlinks to exactly this version). This results in (for pypy3):
```
>>> Test phase: dev-python/versuchung-9999
 * pypy3: running distutils-r1_run_phase python_test
pypy3 setup.py test --verbose
running test
make -C tests PYTHON=/usr/bin/pypy3
make: Entering directory '/var/tmp/portage/dev-python/versuchung-9999/work/versuchung-9999/tests'
Running test python2: two_experiments...: _python_wrapper_setup: python2 is not supported by pypy3 (PYTHON_COMPAT)
make: *** [Makefile:22: py2-two_experiments] Error 127
make: Leaving directory '/var/tmp/portage/dev-python/versuchung-9999/work/versuchung-9999/tests'
error: command 'make' failed with exit status 2
```

Would be nice if the Makefile would use (only) the same interpreter as the one that executes `setup.py`.

**Comment by stettberger** [comment]
At some point, we can just drop the python2 support and avoid the python2 testing altogheter....
